name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project files
        uses: ./.github/actions/setup
        with:
          node-version: 20

      - name: Check Prettier formatting
        run: npm run fmt:check

      - name: Run tests
        run: npm run test:unit
